#include "hash_tables.h"

/**
 * hash_djbe -Implements the djb2 algorithm for hashing strings.
 * @str: The input string.
 *
 * Return: The hash value generated by the djb2 algorithm.
 */
unsigned long int hash_djb2(const unsigned char *str)
{
	unsigned long int hash = 5381;
	int c;

	while ((c = *str++))
		hash = ((hash << 5) + hash) + c;

	return (hash);
}
